# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


###########################
## Added from WhatATheme ##
###########################

### Basic home ###
markdown: kramdown
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# TO BE ADDED LATER FOR GOOGLE SEARCH: Keywords of the Site
#site-keywords: Site, Template, Theme
# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
# Google Analytics
# google-analytics: UA-163806439-1

### About ###
# Name of the Author
author-name: Ariane Dekker
# URL for the Image of the Author
author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
# 60 Words About the Author
author-about: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget pharetra velit, dapibus bibendum ex. Maecenas vitae laoreet mauris, ac luctus metus. Aliquam luctus velit vel ipsum feugiat, vel venenatis mauris hendrerit. Sed at vulputate sapien, eget vehicula dolor. Aliquam volutpat pulvinar neque sit amet sodales.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
# author-url: https://github.com/thedevslot

### SASS ### 
sass:
  sass_dir: _sass
  style: compressed

### Build settings ### 
plugins:
  - jekyll-admin
  - jekyll-feed

### Permalink ### 
permalink: "blog/:title"

### Compress ### 
compress_html:
  clippings: all

### Defaults ### 
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

############################
## Jekyll inital settings ##
############################

title: Ariane Dekker
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"   Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
  ... 
domain: arianedekker.github.io   
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://arianedekker.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: ArianeDekker
#github_username:  ArianeDekker

# # Build settings
# theme: minima
# plugins:
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
